include: ../analysis_options.yaml

linter:
  rules:
    diagnostic_describe_all_properties: false   # For package-level only
    public_member_api_docs: false   # Demo code doesn't document members.
    use_setters_to_change_properties: false   # Conflicts with simple VM methods