# Not ../analysis_options.yaml, which dependency_validator doesn't count as using the package.
include: package:dartender_lints/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false   # Demo code doesn't document members.
