// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Transport twin of the public `RecognitionLevel`.
enum RecognitionLevelMessage: Int, CaseIterable {
  case fast = 0
  case accurate = 1
}

/// Transport twin of the public `CameraPermissionStatus`.
enum CameraPermissionStatusMessage: Int, CaseIterable {
  case granted = 0
  case denied = 1
  case permanentlyDenied = 2
}

/// Transport twin of the public `Rect` region-of-interest (normalized [0,1] top-left).
///
/// Generated class from Pigeon that represents data sent in messages.
struct RegionOfInterestMessage: Hashable, CustomStringConvertible {
  var left: Double
  var top: Double
  var width: Double
  var height: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RegionOfInterestMessage? {
    let left = pigeonVar_list[0] as! Double
    let top = pigeonVar_list[1] as! Double
    let width = pigeonVar_list[2] as! Double
    let height = pigeonVar_list[3] as! Double

    return RegionOfInterestMessage(
      left: left,
      top: top,
      width: width,
      height: height
    )
  }
  func toList() -> [Any?] {
    return [
      left,
      top,
      width,
      height,
    ]
  }
  static func == (lhs: RegionOfInterestMessage, rhs: RegionOfInterestMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.left, rhs.left) && MessagesPigeonInternal.deepEquals(lhs.top, rhs.top) && MessagesPigeonInternal.deepEquals(lhs.width, rhs.width) && MessagesPigeonInternal.deepEquals(lhs.height, rhs.height)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RegionOfInterestMessage")
    MessagesPigeonInternal.deepHash(value: left, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: top, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: width, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: height, hasher: &hasher)
  }

  public var description: String {
    return "RegionOfInterestMessage(left: \(String(describing: left)), top: \(String(describing: top)), width: \(String(describing: width)), height: \(String(describing: height)))"
  }
}

/// Transport twin of the public `TextSightOptions`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct TextSightOptionsMessage: Hashable, CustomStringConvertible {
  var level: RecognitionLevelMessage
  var languages: [String]
  var roi: RegionOfInterestMessage? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TextSightOptionsMessage? {
    let level = pigeonVar_list[0] as! RecognitionLevelMessage
    let languages = pigeonVar_list[1] as! [String]
    let roi: RegionOfInterestMessage? = nilOrValue(pigeonVar_list[2])

    return TextSightOptionsMessage(
      level: level,
      languages: languages,
      roi: roi
    )
  }
  func toList() -> [Any?] {
    return [
      level,
      languages,
      roi,
    ]
  }
  static func == (lhs: TextSightOptionsMessage, rhs: TextSightOptionsMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.level, rhs.level) && MessagesPigeonInternal.deepEquals(lhs.languages, rhs.languages) && MessagesPigeonInternal.deepEquals(lhs.roi, rhs.roi)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("TextSightOptionsMessage")
    MessagesPigeonInternal.deepHash(value: level, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: languages, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: roi, hasher: &hasher)
  }

  public var description: String {
    return "TextSightOptionsMessage(level: \(String(describing: level)), languages: \(String(describing: languages)), roi: \(String(describing: roi)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return RecognitionLevelMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return CameraPermissionStatusMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return RegionOfInterestMessage.fromList(self.readValue() as! [Any?])
    case 132:
      return TextSightOptionsMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? RecognitionLevelMessage {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? CameraPermissionStatusMessage {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? RegionOfInterestMessage {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? TextSightOptionsMessage {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// The typed control channel. Per-frame results stream over a plain
/// EventChannel and the preview is a texture — neither rides this API.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol TextSightHostApi {
  /// Opens the camera with [options]; returns the preview texture id.
  func initialize(options: TextSightOptionsMessage, completion: @escaping (Result<Int64, Error>) -> Void)
  /// Begins frame delivery and recognition.
  func start(completion: @escaping (Result<Void, Error>) -> Void)
  /// Pauses recognition, keeping the session open for a later [start].
  func stop(completion: @escaping (Result<Void, Error>) -> Void)
  /// Releases the camera and texture.
  func dispose(completion: @escaping (Result<Void, Error>) -> Void)
  /// Reports the current camera-permission status without prompting.
  func checkCameraPermission() throws -> CameraPermissionStatusMessage
  /// Prompts for camera permission when it has not yet been decided, resolving to the resulting status.
  func requestCameraPermission(completion: @escaping (Result<CameraPermissionStatusMessage, Error>) -> Void)
  /// Restricts recognition to [roi], or clears it (whole frame) when null.
  func setRegionOfInterest(roi: RegionOfInterestMessage?) throws
  /// Switches the recognizer's accuracy/latency level.
  func setRecognitionLevel(level: RecognitionLevelMessage) throws
  /// Replaces the preferred recognition languages (BCP-47 tags).
  func setLanguages(languages: [String]) throws
  /// Turns the camera torch on or off.
  func setTorchEnabled(enabled: Bool) throws
  /// Ensures the recognition model is present (fetching the unbundled ML Kit model via
  /// Google Play Services when needed) and returns the terminal readiness state.
  func ensureModelReady(completion: @escaping (Result<[String: Any?], Error>) -> Void)
  /// Recognizes text in the encoded image [bytes] (PNG/JPEG/…), honouring [options].
  func recognizeImage(bytes: FlutterStandardTypedData, options: TextSightOptionsMessage, completion: @escaping (Result<[String: Any?], Error>) -> Void)
  /// Recognizes text in the image at file [path], honouring [options].
  func recognizePath(path: String, options: TextSightOptionsMessage, completion: @escaping (Result<[String: Any?], Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class TextSightHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `TextSightHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: TextSightHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Opens the camera with [options]; returns the preview texture id.
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.text_sight.TextSightHostApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let optionsArg = args[0] as! TextSightOptionsMessage
        api.initialize(options: optionsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    /// Begins frame delivery and recognition.
    let startChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.text_sight.TextSightHostApi.start\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startChannel.setMessageHandler { _, reply in
        api.start { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startChannel.setMessageHandler(nil)
    }
    /// Pauses recognition, keeping the session open for a later [start].
    let stopChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.text_sight.TextSightHostApi.stop\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopChannel.setMessageHandler { _, reply in
        api.stop { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopChannel.setMessageHandler(nil)
    }
    /// Releases the camera and texture.
    let disposeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.text_sight.TextSightHostApi.dispose\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeChannel.setMessageHandler { _, reply in
        api.dispose { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      disposeChannel.setMessageHandler(nil)
    }
    /// Reports the current camera-permission status without prompting.
    let checkCameraPermissionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.text_sight.TextSightHostApi.checkCameraPermission\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      checkCameraPermissionChannel.setMessageHandler { _, reply in
        do {
          let result = try api.checkCameraPermission()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      checkCameraPermissionChannel.setMessageHandler(nil)
    }
    /// Prompts for camera permission when it has not yet been decided, resolving to the resulting status.
    let requestCameraPermissionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.text_sight.TextSightHostApi.requestCameraPermission\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestCameraPermissionChannel.setMessageHandler { _, reply in
        api.requestCameraPermission { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestCameraPermissionChannel.setMessageHandler(nil)
    }
    /// Restricts recognition to [roi], or clears it (whole frame) when null.
    let setRegionOfInterestChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.text_sight.TextSightHostApi.setRegionOfInterest\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setRegionOfInterestChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let roiArg: RegionOfInterestMessage? = nilOrValue(args[0])
        do {
          try api.setRegionOfInterest(roi: roiArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setRegionOfInterestChannel.setMessageHandler(nil)
    }
    /// Switches the recognizer's accuracy/latency level.
    let setRecognitionLevelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.text_sight.TextSightHostApi.setRecognitionLevel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setRecognitionLevelChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let levelArg = args[0] as! RecognitionLevelMessage
        do {
          try api.setRecognitionLevel(level: levelArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setRecognitionLevelChannel.setMessageHandler(nil)
    }
    /// Replaces the preferred recognition languages (BCP-47 tags).
    let setLanguagesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.text_sight.TextSightHostApi.setLanguages\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setLanguagesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let languagesArg = args[0] as! [String]
        do {
          try api.setLanguages(languages: languagesArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setLanguagesChannel.setMessageHandler(nil)
    }
    /// Turns the camera torch on or off.
    let setTorchEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.text_sight.TextSightHostApi.setTorchEnabled\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setTorchEnabledChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enabledArg = args[0] as! Bool
        do {
          try api.setTorchEnabled(enabled: enabledArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setTorchEnabledChannel.setMessageHandler(nil)
    }
    /// Ensures the recognition model is present (fetching the unbundled ML Kit model via
    /// Google Play Services when needed) and returns the terminal readiness state.
    let ensureModelReadyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.text_sight.TextSightHostApi.ensureModelReady\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      ensureModelReadyChannel.setMessageHandler { _, reply in
        api.ensureModelReady { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      ensureModelReadyChannel.setMessageHandler(nil)
    }
    /// Recognizes text in the encoded image [bytes] (PNG/JPEG/…), honouring [options].
    let recognizeImageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.text_sight.TextSightHostApi.recognizeImage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      recognizeImageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let bytesArg = args[0] as! FlutterStandardTypedData
        let optionsArg = args[1] as! TextSightOptionsMessage
        api.recognizeImage(bytes: bytesArg, options: optionsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      recognizeImageChannel.setMessageHandler(nil)
    }
    /// Recognizes text in the image at file [path], honouring [options].
    let recognizePathChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.text_sight.TextSightHostApi.recognizePath\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      recognizePathChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        let optionsArg = args[1] as! TextSightOptionsMessage
        api.recognizePath(path: pathArg, options: optionsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      recognizePathChannel.setMessageHandler(nil)
    }
  }
}
