// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

/// Transport twin of the public `RecognitionLevel`.
enum RecognitionLevelMessage { fast, accurate }

/// Transport twin of the public `CameraPermissionStatus`.
enum CameraPermissionStatusMessage { granted, denied, permanentlyDenied }

/// Transport twin of the public `Rect` region-of-interest (normalized [0,1] top-left).
class RegionOfInterestMessage {
  RegionOfInterestMessage({
    required this.left,
    required this.top,
    required this.width,
    required this.height,
  });

  double left;

  double top;

  double width;

  double height;

  List<Object?> _toList() {
    return <Object?>[left, top, width, height];
  }

  Object encode() {
    return _toList();
  }

  static RegionOfInterestMessage decode(Object result) {
    result as List<Object?>;
    return RegionOfInterestMessage(
      left: result[0]! as double,
      top: result[1]! as double,
      width: result[2]! as double,
      height: result[3]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RegionOfInterestMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(left, other.left) &&
        _deepEquals(top, other.top) &&
        _deepEquals(width, other.width) &&
        _deepEquals(height, other.height);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'RegionOfInterestMessage(left: $left, top: $top, width: $width, height: $height)';
  }
}

/// Transport twin of the public `TextSightOptions`.
class TextSightOptionsMessage {
  TextSightOptionsMessage({required this.level, required this.languages, this.roi});

  RecognitionLevelMessage level;

  List<String> languages;

  RegionOfInterestMessage? roi;

  List<Object?> _toList() {
    return <Object?>[level, languages, roi];
  }

  Object encode() {
    return _toList();
  }

  static TextSightOptionsMessage decode(Object result) {
    result as List<Object?>;
    return TextSightOptionsMessage(
      level: result[0]! as RecognitionLevelMessage,
      languages: (result[1]! as List<Object?>).cast<String>(),
      roi: result[2] as RegionOfInterestMessage?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TextSightOptionsMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(level, other.level) &&
        _deepEquals(languages, other.languages) &&
        _deepEquals(roi, other.roi);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'TextSightOptionsMessage(level: $level, languages: $languages, roi: $roi)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is RecognitionLevelMessage) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is CameraPermissionStatusMessage) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is RegionOfInterestMessage) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is TextSightOptionsMessage) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : RecognitionLevelMessage.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : CameraPermissionStatusMessage.values[value];
      case 131:
        return RegionOfInterestMessage.decode(readValue(buffer)!);
      case 132:
        return TextSightOptionsMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// The typed control channel. Per-frame results stream over a plain
/// EventChannel and the preview is a texture — neither rides this API.
class TextSightHostApi {
  /// Constructor for [TextSightHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  TextSightHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
    : pigeonVar_binaryMessenger = binaryMessenger,
      pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
          ? '.$messageChannelSuffix'
          : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Opens the camera with [options]; returns the preview texture id.
  Future<int> initialize(TextSightOptionsMessage options) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.text_sight.TextSightHostApi.initialize$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[options]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as int;
  }

  /// Begins frame delivery and recognition.
  Future<void> start() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.text_sight.TextSightHostApi.start$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Pauses recognition, keeping the session open for a later [start].
  Future<void> stop() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.text_sight.TextSightHostApi.stop$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Releases the camera and texture.
  Future<void> dispose() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.text_sight.TextSightHostApi.dispose$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Reports the current camera-permission status without prompting.
  Future<CameraPermissionStatusMessage> checkCameraPermission() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.text_sight.TextSightHostApi.checkCameraPermission$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as CameraPermissionStatusMessage;
  }

  /// Prompts for camera permission when it has not yet been decided, resolving to the resulting status.
  Future<CameraPermissionStatusMessage> requestCameraPermission() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.text_sight.TextSightHostApi.requestCameraPermission$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as CameraPermissionStatusMessage;
  }

  /// Restricts recognition to [roi], or clears it (whole frame) when null.
  Future<void> setRegionOfInterest(RegionOfInterestMessage? roi) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.text_sight.TextSightHostApi.setRegionOfInterest$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[roi]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Switches the recognizer's accuracy/latency level.
  Future<void> setRecognitionLevel(RecognitionLevelMessage level) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.text_sight.TextSightHostApi.setRecognitionLevel$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[level]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Replaces the preferred recognition languages (BCP-47 tags).
  Future<void> setLanguages(List<String> languages) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.text_sight.TextSightHostApi.setLanguages$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[languages]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Turns the camera torch on or off.
  Future<void> setTorchEnabled(bool enabled) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.text_sight.TextSightHostApi.setTorchEnabled$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[enabled]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Ensures the recognition model is present (fetching the unbundled ML Kit model via
  /// Google Play Services when needed) and returns the terminal readiness state.
  Future<Map<String, Object?>> ensureModelReady() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.text_sight.TextSightHostApi.ensureModelReady$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as Map<Object?, Object?>).cast<String, Object?>();
  }

  /// Recognizes text in the encoded image [bytes] (PNG/JPEG/…), honouring [options].
  Future<Map<String, Object?>> recognizeImage(
    Uint8List bytes,
    TextSightOptionsMessage options,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.text_sight.TextSightHostApi.recognizeImage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[bytes, options]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as Map<Object?, Object?>).cast<String, Object?>();
  }

  /// Recognizes text in the image at file [path], honouring [options].
  Future<Map<String, Object?>> recognizePath(String path, TextSightOptionsMessage options) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.text_sight.TextSightHostApi.recognizePath$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[path, options]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as Map<Object?, Object?>).cast<String, Object?>();
  }
}
