// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

/// Transport twin of the public `RecognitionLevel`.
enum RecognitionLevelMessage { fast, accurate }

/// Transport twin of the public `ConfidenceScale`.
enum ConfidenceScaleMessage { visionGraded, visionCoarse, mlKit }

/// Transport twin of the public `CaptureResolution`.
enum CaptureResolutionMessage { low, medium, high }

/// Transport twin of the public `CameraPermissionStatus`.
enum CameraPermissionStatusMessage { granted, denied, permanentlyDenied }

/// Transport twin of the public `SessionPauseReason`.
enum SessionPauseReasonMessage { appBackgrounded, interrupted }

/// Transport twin of the public `Rect` region-of-interest (normalized [0,1] top-left).
class RegionOfInterestMessage {
  RegionOfInterestMessage({
    required this.left,
    required this.top,
    required this.width,
    required this.height,
  });

  double left;

  double top;

  double width;

  double height;

  List<Object?> _toList() {
    return <Object?>[left, top, width, height];
  }

  Object encode() {
    return _toList();
  }

  static RegionOfInterestMessage decode(Object result) {
    result as List<Object?>;
    return RegionOfInterestMessage(
      left: result[0]! as double,
      top: result[1]! as double,
      width: result[2]! as double,
      height: result[3]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RegionOfInterestMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(left, other.left) &&
        _deepEquals(top, other.top) &&
        _deepEquals(width, other.width) &&
        _deepEquals(height, other.height);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'RegionOfInterestMessage(left: $left, top: $top, width: $width, height: $height)';
  }
}

/// Transport twin of the public `TextSightOptions`.
class TextSightOptionsMessage {
  TextSightOptionsMessage({
    required this.level,
    required this.usesLanguageCorrection,
    required this.languages,
    required this.minimumTextHeight,
    this.roi,
  });

  RecognitionLevelMessage level;

  /// Whether the recognizer fixes likely misreads against a lexicon. Vision only.
  bool usesLanguageCorrection;

  List<String> languages;

  /// Smallest text to read, as a fraction of the scan box. Vision shrinks the image to suit, so 0
  /// keeps every pixel. ML Kit has no such dial, so Android ignores it.
  double minimumTextHeight;

  RegionOfInterestMessage? roi;

  List<Object?> _toList() {
    return <Object?>[level, usesLanguageCorrection, languages, minimumTextHeight, roi];
  }

  Object encode() {
    return _toList();
  }

  static TextSightOptionsMessage decode(Object result) {
    result as List<Object?>;
    return TextSightOptionsMessage(
      level: result[0]! as RecognitionLevelMessage,
      usesLanguageCorrection: result[1]! as bool,
      languages: (result[2]! as List<Object?>).cast<String>(),
      minimumTextHeight: result[3]! as double,
      roi: result[4] as RegionOfInterestMessage?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TextSightOptionsMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(level, other.level) &&
        _deepEquals(usesLanguageCorrection, other.usesLanguageCorrection) &&
        _deepEquals(languages, other.languages) &&
        _deepEquals(minimumTextHeight, other.minimumTextHeight) &&
        _deepEquals(roi, other.roi);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'TextSightOptionsMessage(level: $level, usesLanguageCorrection: $usesLanguageCorrection, languages: $languages, minimumTextHeight: $minimumTextHeight, roi: $roi)';
  }
}

/// Transport twin of the public sealed `TextSightSessionState`, one case per state. Pigeon needs
/// the parent empty.
sealed class SessionStateMessage {}

/// Twin of `SessionIdle`.
class SessionIdleMessage extends SessionStateMessage {
  SessionIdleMessage();

  List<Object?> _toList() {
    return <Object?>[];
  }

  Object encode() {
    return _toList();
  }

  static SessionIdleMessage decode(Object result) {
    result as List<Object?>;
    return SessionIdleMessage();
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SessionIdleMessage || other.runtimeType != runtimeType) {
      return false;
    }
    return true;
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'SessionIdleMessage()';
  }
}

/// Twin of `SessionActive`.
class SessionActiveMessage extends SessionStateMessage {
  SessionActiveMessage();

  List<Object?> _toList() {
    return <Object?>[];
  }

  Object encode() {
    return _toList();
  }

  static SessionActiveMessage decode(Object result) {
    result as List<Object?>;
    return SessionActiveMessage();
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SessionActiveMessage || other.runtimeType != runtimeType) {
      return false;
    }
    return true;
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'SessionActiveMessage()';
  }
}

/// Twin of `SessionPaused`.
class SessionPausedMessage extends SessionStateMessage {
  SessionPausedMessage({required this.reason, this.details});

  SessionPauseReasonMessage reason;

  String? details;

  List<Object?> _toList() {
    return <Object?>[reason, details];
  }

  Object encode() {
    return _toList();
  }

  static SessionPausedMessage decode(Object result) {
    result as List<Object?>;
    return SessionPausedMessage(
      reason: result[0]! as SessionPauseReasonMessage,
      details: result[1] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SessionPausedMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(reason, other.reason) && _deepEquals(details, other.details);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'SessionPausedMessage(reason: $reason, details: $details)';
  }
}

/// Twin of `SessionFailed`.
class SessionFailedMessage extends SessionStateMessage {
  SessionFailedMessage({this.details});

  String? details;

  List<Object?> _toList() {
    return <Object?>[details];
  }

  Object encode() {
    return _toList();
  }

  static SessionFailedMessage decode(Object result) {
    result as List<Object?>;
    return SessionFailedMessage(details: result[0] as String?);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SessionFailedMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(details, other.details);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'SessionFailedMessage(details: $details)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is RecognitionLevelMessage) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is ConfidenceScaleMessage) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is CaptureResolutionMessage) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else if (value is CameraPermissionStatusMessage) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    } else if (value is SessionPauseReasonMessage) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    } else if (value is RegionOfInterestMessage) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is TextSightOptionsMessage) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is SessionIdleMessage) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is SessionActiveMessage) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else if (value is SessionPausedMessage) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else if (value is SessionFailedMessage) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : RecognitionLevelMessage.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : ConfidenceScaleMessage.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : CaptureResolutionMessage.values[value];
      case 132:
        final value = readValue(buffer) as int?;
        return value == null ? null : CameraPermissionStatusMessage.values[value];
      case 133:
        final value = readValue(buffer) as int?;
        return value == null ? null : SessionPauseReasonMessage.values[value];
      case 134:
        return RegionOfInterestMessage.decode(readValue(buffer)!);
      case 135:
        return TextSightOptionsMessage.decode(readValue(buffer)!);
      case 136:
        return SessionIdleMessage.decode(readValue(buffer)!);
      case 137:
        return SessionActiveMessage.decode(readValue(buffer)!);
      case 138:
        return SessionPausedMessage.decode(readValue(buffer)!);
      case 139:
        return SessionFailedMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// The typed control channel. Per-frame results stream over a plain
/// EventChannel and the preview is a texture. Neither rides this API.
class TextSightHostApi {
  /// Constructor for [TextSightHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  TextSightHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
    : pigeonVar_binaryMessenger = binaryMessenger,
      pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
          ? '.$messageChannelSuffix'
          : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Opens the camera with [options] at [resolution]. Returns the preview texture id.
  ///
  /// Reopening an already-open session is fine: the old one is released first, so the id this
  /// returns replaces the previous one. Recognition comes back off until [start]. Resolution rides
  /// here, not on the options, because it cannot change mid-session.
  Future<int> initialize(
    TextSightOptionsMessage options,
    CaptureResolutionMessage resolution,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.text_sight.TextSightHostApi.initialize$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[
      options,
      resolution,
    ]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as int;
  }

  /// Begins frame delivery and recognition. Not `@async`: both natives only flip a flag, and the
  /// Dart signature is `Future<void>` either way.
  Future<void> start() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.text_sight.TextSightHostApi.start$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Pauses recognition, keeping the session open for a later [start]. Not `@async`, as [start].
  Future<void> pauseRecognition() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.text_sight.TextSightHostApi.pauseRecognition$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Releases the camera and texture. Idempotent, so calling it with nothing open is fine.
  Future<void> dispose() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.text_sight.TextSightHostApi.dispose$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Reports the current camera-permission status without prompting.
  Future<CameraPermissionStatusMessage> checkCameraPermission() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.text_sight.TextSightHostApi.checkCameraPermission$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as CameraPermissionStatusMessage;
  }

  /// Prompts for camera permission when it has not yet been decided, resolving to the resulting status.
  Future<CameraPermissionStatusMessage> requestCameraPermission() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.text_sight.TextSightHostApi.requestCameraPermission$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as CameraPermissionStatusMessage;
  }

  /// Replaces the recognizer settings on an open session. Resolution is not in here, it cannot
  /// change mid-session, so it rides [initialize] instead.
  Future<void> setOptions(TextSightOptionsMessage options) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.text_sight.TextSightHostApi.setOptions$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[options]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Turns the camera torch on or off.
  Future<void> setTorchEnabled(bool enabled) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.text_sight.TextSightHostApi.setTorchEnabled$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[enabled]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// What a per-line confidence means on this device. Fixed once the engine is picked, so the
  /// Dart side reads it once and caches.
  Future<ConfidenceScaleMessage> confidenceScale() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.text_sight.TextSightHostApi.confidenceScale$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as ConfidenceScaleMessage;
  }

  /// Ensures the recognition model is present (fetching the unbundled ML Kit model via
  /// Google Play Services when needed) and returns the terminal readiness state.
  Future<Map<String, Object?>> ensureModelReady() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.text_sight.TextSightHostApi.ensureModelReady$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as Map<Object?, Object?>).cast<String, Object?>();
  }

  /// Recognizes text in the encoded image [bytes] (PNG/JPEG/…), honouring [options].
  Future<Map<String, Object?>> recognizeImage(
    Uint8List bytes,
    TextSightOptionsMessage options,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.text_sight.TextSightHostApi.recognizeImage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[bytes, options]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as Map<Object?, Object?>).cast<String, Object?>();
  }

  /// Recognizes text in the image at file [path], honouring [options].
  Future<Map<String, Object?>> recognizePath(String path, TextSightOptionsMessage options) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.text_sight.TextSightHostApi.recognizePath$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[path, options]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as Map<Object?, Object?>).cast<String, Object?>();
  }
}

/// Native-to-Dart notifications: rare and typed, so they ride Pigeon rather than an EventChannel.
abstract class TextSightFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// Fired on every actual session transition native makes or observes.
  void onSessionStateChanged(SessionStateMessage state);

  static void setUp(
    TextSightFlutterApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.text_sight.TextSightFlutterApi.onSessionStateChanged$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final SessionStateMessage arg_state = args[0]! as SessionStateMessage;
          try {
            api.onSessionStateChanged(arg_state);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}
